---
# skip jinja testing
- name: Get user info for "{{ ansible_user_id }}"
  ansible.builtin.user:
    user: "{{ ansible_user_id }}"
    state: present
  register: user_info

- name: Normalize default paths
  ansible.builtin.set_fact:
    frigate_config_path: "{{ frigate_config_path | replace('~', user_info.home) }}"
    frigate_storage_path: "{{ frigate_storage_path | replace('~', user_info.home) }}"

- name: Create Frigate directories
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    mode: "0750"
  loop:
    - "{{ frigate_config_path }}"
    - "{{ frigate_storage_path }}"

- name: Put container related files on the host
  ansible.builtin.template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    mode: "0640"
  loop:
    - { src: frigate.container.j2, dest: "{{ user_info.home }}/.config/containers/systemd/frigate.container" }
    - { src: frigate.pod.j2, dest: "{{ user_info.home }}/.config/containers/systemd/frigate.pod" }

- name: Start the container service
  ansible.builtin.systemd:
    name: frigate
    state: started
    scope: user
    enabled: true
    daemon_reload: true
