---
- name: Verify web server
  hosts: all
  tasks:
    - name: Wait for the web server to start
      ansible.builtin.wait_for:
        port: 5000
        delay: 10
        timeout: 30

    - name: Verify that the http web server is serving content
      ansible.builtin.uri:
        url: http://localhost:5000/api/
        return_content: true
      register: web_content

    - name: Check if the web server is up
      ansible.builtin.assert:
        that:
          - "'Frigate is running. Alive and healthy!' in web_content.content"
